USE [master]
GO

/****** Object:  Database [MyNotesDB]    Script Date: 6/20/2021 7:04:46 PM ******/
CREATE DATABASE [MyNotesDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MyNotesDB', FILENAME = N'C:\Program Files\Database\MyNotesDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MyNotesDB_log', FILENAME = N'C:\Program Files\Database\MyNotesDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MyNotesDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MyNotesDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MyNotesDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MyNotesDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MyNotesDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MyNotesDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [MyNotesDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MyNotesDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MyNotesDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MyNotesDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MyNotesDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MyNotesDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MyNotesDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MyNotesDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MyNotesDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MyNotesDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MyNotesDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MyNotesDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MyNotesDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MyNotesDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MyNotesDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MyNotesDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MyNotesDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MyNotesDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MyNotesDB] SET  MULTI_USER 
GO

ALTER DATABASE [MyNotesDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MyNotesDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MyNotesDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MyNotesDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MyNotesDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MyNotesDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [MyNotesDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MyNotesDB] SET  READ_WRITE 
GO


